language: python
cache: pip
python:
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7-dev'
install:
    - pip install -r requirements-dev.txt
script:
    - flake8
    - xvfb-run nose2 --with-coverage
after_success:
    - coveralls
